/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../app/hero-search.service';
import * as import4 from '../../app/hero-search.component';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from '@angular/http/src/http';
import * as import10 from '@angular/router/src/router';
import * as import11 from '@angular/core/src/metadata/view';
import * as import12 from '@angular/core/src/linker/component_factory';
import * as import13 from './hero-search.component.css.shim';
import * as import14 from '../../app/contact/highlight.directive';
import * as import15 from '@angular/common/src/directives/ng_for';
import * as import16 from '@angular/common/src/pipes/async_pipe';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
var renderType_HeroSearchComponent_Host:import0.RenderComponentType = (null as any);
class _View_HeroSearchComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeroSearchService_0_4:import3.HeroSearchService;
  _HeroSearchComponent_0_5:import4.HeroSearchComponent;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroSearchComponent_Host0,renderType_HeroSearchComponent_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('hero-search',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HeroSearchComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeroSearchService_0_4 = new import3.HeroSearchService(this.parentInjector.get(import9.Http));
    this._HeroSearchComponent_0_5 = new import4.HeroSearchComponent(this._HeroSearchService_0_4,this.parentInjector.get(import10.Router));
    this._appEl_0.initComponent(this._HeroSearchComponent_0_5,([] as any[]),compView_0);
    compView_0.create(this._HeroSearchComponent_0_5,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HeroSearchService) && (0 === requestNodeIndex))) { return this._HeroSearchService_0_4; }
    if (((token === import4.HeroSearchComponent) && (0 === requestNodeIndex))) { return this._HeroSearchComponent_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeroSearchComponent_0_5.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeroSearchComponent_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HeroSearchComponent_Host === (null as any))) { (renderType_HeroSearchComponent_Host = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HeroSearchComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeroSearchComponentNgFactory:import12.ComponentFactory<import4.HeroSearchComponent> = new import12.ComponentFactory<import4.HeroSearchComponent>('hero-search',viewFactory_HeroSearchComponent_Host0,import4.HeroSearchComponent);
const styles_HeroSearchComponent:any[] = [import13.styles];
var renderType_HeroSearchComponent:import0.RenderComponentType = (null as any);
class _View_HeroSearchComponent0 extends import1.AppView<import4.HeroSearchComponent> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _HighlightDirective_5_3:import14.HighlightDirective;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _anchor_9:any;
  /*private*/ _appEl_9:import2.AppElement;
  _TemplateRef_9_5:any;
  _NgFor_9_6:import15.NgFor;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _pipe_async_0:import16.AsyncPipe;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroSearchComponent0,renderType_HeroSearchComponent,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'id','search-component');
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h4',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'Hero Search',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'input',(null as any));
    this.renderer.setElementAttribute(this._el_5,'id','search-box');
    this._HighlightDirective_5_3 = new import14.HighlightDirective(this.renderer,new import17.ElementRef(this._el_5));
    this._text_6 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_0,'div',(null as any));
    this._text_8 = this.renderer.createText(this._el_7,'\n    ',(null as any));
    this._anchor_9 = this.renderer.createTemplateAnchor(this._el_7,(null as any));
    this._appEl_9 = new import2.AppElement(9,7,this,this._anchor_9);
    this._TemplateRef_9_5 = new import18.TemplateRef_(this._appEl_9,viewFactory_HeroSearchComponent1);
    this._NgFor_9_6 = new import15.NgFor(this._appEl_9.vcRef,this._TemplateRef_9_5,this.parentInjector.get(import19.IterableDiffers),this.ref);
    this._text_10 = this.renderer.createText(this._el_7,'\n  ',(null as any));
    this._text_11 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_12 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_5,'keyup',this.eventHandler(this._handle_keyup_5_0.bind(this)));
    this._pipe_async_0 = new import16.AsyncPipe(this.ref);
    this._expr_1 = import8.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._anchor_9,
      this._text_10,
      this._text_11,
      this._text_12
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import14.HighlightDirective) && (5 === requestNodeIndex))) { return this._HighlightDirective_5_3; }
    if (((token === import18.TemplateRef) && (9 === requestNodeIndex))) { return this._TemplateRef_9_5; }
    if (((token === import15.NgFor) && (9 === requestNodeIndex))) { return this._NgFor_9_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import8.SimpleChange} = (null as any);
    const valUnwrapper:any = new import8.ValueUnwrapper();
    changes = (null as any);
    valUnwrapper.reset();
    const currVal_1:any = valUnwrapper.unwrap(this._pipe_async_0.transform(this.context.heroes));
    if ((valUnwrapper.hasWrappedValue || import5.checkBinding(throwOnChange,this._expr_1,currVal_1))) {
      this._NgFor_9_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import8.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_9_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_9_6.ngDoCheck(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._pipe_async_0.ngOnDestroy();
  }
  private _handle_keyup_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.search(this._el_5.value)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HeroSearchComponent0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<import4.HeroSearchComponent> {
  if ((renderType_HeroSearchComponent === (null as any))) { (renderType_HeroSearchComponent = viewUtils.createRenderComponentType('',0,import11.ViewEncapsulation.Emulated,styles_HeroSearchComponent,{})); }
  return new _View_HeroSearchComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_HeroSearchComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_1:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroSearchComponent1,renderType_HeroSearchComponent,import7.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','search-result');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_1 = import8.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = import5.interpolate(1,'\n      ',this.context.$implicit.name,'\n    ');
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.gotoDetail(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeroSearchComponent1(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeroSearchComponent1(viewUtils,parentInjector,declarationEl);
}