/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../app/heroes.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '@angular/router/src/router';
import * as import9 from '../../app/hero.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './heroes.component.css.shim';
import * as import13 from '../../app/contact/highlight.directive';
import * as import14 from '@angular/common/src/directives/ng_for';
import * as import15 from '@angular/common/src/directives/ng_if';
import * as import16 from '@angular/common/src/pipes/uppercase_pipe';
import * as import17 from '@angular/core/src/linker/element_ref';
import * as import18 from '@angular/core/src/linker/template_ref';
import * as import19 from '@angular/core/src/change_detection/differs/iterable_differs';
var renderType_HeroesComponent_Host:import0.RenderComponentType = (null as any);
class _View_HeroesComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _HeroesComponent_0_4:import3.HeroesComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroesComponent_Host0,renderType_HeroesComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('my-heroes',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HeroesComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HeroesComponent_0_4 = new import3.HeroesComponent(this.parentInjector.get(import8.Router),this.parentInjector.get(import9.HeroService));
    this._appEl_0.initComponent(this._HeroesComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._HeroesComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.HeroesComponent) && (0 === requestNodeIndex))) { return this._HeroesComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._HeroesComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HeroesComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_HeroesComponent_Host === (null as any))) { (renderType_HeroesComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HeroesComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const HeroesComponentNgFactory:import11.ComponentFactory<import3.HeroesComponent> = new import11.ComponentFactory<import3.HeroesComponent>('my-heroes',viewFactory_HeroesComponent_Host0,import3.HeroesComponent);
const styles_HeroesComponent:any[] = [import12.styles];
var renderType_HeroesComponent:import0.RenderComponentType = (null as any);
class _View_HeroesComponent0 extends import1.AppView<import3.HeroesComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _el_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _HighlightDirective_8_3:import13.HighlightDirective;
  _text_9:any;
  _el_10:any;
  _text_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _anchor_16:any;
  /*private*/ _appEl_16:import2.AppElement;
  _TemplateRef_16_5:any;
  _NgFor_16_6:import14.NgFor;
  _text_17:any;
  _text_18:any;
  _anchor_19:any;
  /*private*/ _appEl_19:import2.AppElement;
  _TemplateRef_19_5:any;
  _NgIf_19_6:import15.NgIf;
  _text_20:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  _pipe_uppercase_0:import16.UpperCasePipe;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroesComponent0,renderType_HeroesComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h3',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'My Heroes',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_3 = this.renderer.createElement(parentRenderNode,'div',(null as any));
    this._text_4 = this.renderer.createText(this._el_3,'\n  ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'label',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'Hero name:',(null as any));
    this._text_7 = this.renderer.createText(this._el_3,' ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_3,'input',(null as any));
    this._HighlightDirective_8_3 = new import13.HighlightDirective(this.renderer,new import17.ElementRef(this._el_8));
    this._text_9 = this.renderer.createText(this._el_3,'\n  ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_3,'button',(null as any));
    this._text_11 = this.renderer.createText(this._el_10,'\n    Add\n  ',(null as any));
    this._text_12 = this.renderer.createText(this._el_3,'\n',(null as any));
    this._text_13 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_14 = this.renderer.createElement(parentRenderNode,'ul',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','heroes');
    this._text_15 = this.renderer.createText(this._el_14,'\n    ',(null as any));
    this._anchor_16 = this.renderer.createTemplateAnchor(this._el_14,(null as any));
    this._appEl_16 = new import2.AppElement(16,14,this,this._anchor_16);
    this._TemplateRef_16_5 = new import18.TemplateRef_(this._appEl_16,viewFactory_HeroesComponent1);
    this._NgFor_16_6 = new import14.NgFor(this._appEl_16.vcRef,this._TemplateRef_16_5,this.parentInjector.get(import19.IterableDiffers),this.ref);
    this._text_17 = this.renderer.createText(this._el_14,'\n',(null as any));
    this._text_18 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._anchor_19 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_19 = new import2.AppElement(19,(null as any),this,this._anchor_19);
    this._TemplateRef_19_5 = new import18.TemplateRef_(this._appEl_19,viewFactory_HeroesComponent2);
    this._NgIf_19_6 = new import15.NgIf(this._appEl_19.vcRef,this._TemplateRef_19_5);
    this._text_20 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_10,'click',this.eventHandler(this._handle_click_10_0.bind(this)));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._pipe_uppercase_0 = new import16.UpperCasePipe();
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._anchor_16,
      this._text_17,
      this._text_18,
      this._anchor_19,
      this._text_20
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import13.HighlightDirective) && (8 === requestNodeIndex))) { return this._HighlightDirective_8_3; }
    if (((token === import18.TemplateRef) && (16 === requestNodeIndex))) { return this._TemplateRef_16_5; }
    if (((token === import14.NgFor) && (16 === requestNodeIndex))) { return this._NgFor_16_6; }
    if (((token === import18.TemplateRef) && (19 === requestNodeIndex))) { return this._TemplateRef_19_5; }
    if (((token === import15.NgIf) && (19 === requestNodeIndex))) { return this._NgIf_19_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    changes = (null as any);
    const currVal_1:any = this.context.heroes;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgFor_16_6.ngForOf = currVal_1;
      if ((changes === (null as any))) { (changes = {}); }
      changes['ngForOf'] = new import7.SimpleChange(this._expr_1,currVal_1);
      this._expr_1 = currVal_1;
    }
    if ((changes !== (null as any))) { this._NgFor_16_6.ngOnChanges(changes); }
    if (!throwOnChange) { this._NgFor_16_6.ngDoCheck(); }
    const currVal_2:any = this.context.selectedHero;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_19_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.context.add(this._el_8.value);
    const pd_0:any = ((<any>(this._el_8.value = '')) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HeroesComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.HeroesComponent> {
  if ((renderType_HeroesComponent === (null as any))) { (renderType_HeroesComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_HeroesComponent,{})); }
  return new _View_HeroesComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_HeroesComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroesComponent1,renderType_HeroesComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'li',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n         ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'span',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','badge');
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,' \n         ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'span',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n         ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_8,'class','delete');
    this._text_9 = this.renderer.createText(this._el_8,'x',(null as any));
    this._text_10 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_0,'click',this.eventHandler(this._handle_click_0_0.bind(this)));
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_8,'click',this.eventHandler(this._handle_click_8_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10
    ]
    ,[
      disposable_0,
      disposable_1
    ]
    ,([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = (this.context.$implicit === this.parent.context.selectedHero);
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_0,'selected',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,'',this.context.$implicit.id,'');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_3,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,'',this.context.$implicit.name,'');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_6,currVal_3);
      this._expr_3 = currVal_3;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onSelect(this.context.$implicit)) !== false);
    return (true && pd_0);
  }
  private _handle_click_8_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    this.parent.context.delete(this.context.$implicit);
    const pd_0:any = ((<any>$event.stopPropagation()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeroesComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeroesComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_HeroesComponent2 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _text_7:any;
  _pipe_uppercase_0_0:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_HeroesComponent2,renderType_HeroesComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h2',(null as any));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'button',(null as any));
    this._text_6 = this.renderer.createText(this._el_5,'View Details',(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._pipe_uppercase_0_0 = import4.pureProxy1((<_View_HeroesComponent0>this.parent)._pipe_uppercase_0.transform.bind((<_View_HeroesComponent0>this.parent)._pipe_uppercase_0));
    this._expr_0 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_5,'click',this.eventHandler(this._handle_click_5_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7
    ]
    ,[disposable_0],([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const valUnwrapper:any = new import7.ValueUnwrapper();
    this.detectContentChildrenChanges(throwOnChange);
    valUnwrapper.reset();
    const currVal_0:any = import4.interpolate(1,'\n    ',valUnwrapper.unwrap(import4.castByValue(this._pipe_uppercase_0_0,(<_View_HeroesComponent0>this.parent)._pipe_uppercase_0.transform)(this.parent.context.selectedHero.name)),' is my hero\n  ');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_0,currVal_0))) {
      this.renderer.setText(this._text_3,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  private _handle_click_5_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.gotoDetail()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_HeroesComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_HeroesComponent2(viewUtils,parentInjector,declarationEl);
}