/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

export const styles:any[] = ['.ng-valid[required][_ngcontent-%COMP%] {\r\n  border-left: 5px solid #42A948; \r\n}\r\n.ng-invalid[_ngcontent-%COMP%] {\r\n  border-left: 5px solid #a94442; \r\n}\r\n.alert[_ngcontent-%COMP%] {\r\n  padding: 15px;\r\n  margin: 8px 0;\r\n  border: 1px solid transparent;\r\n  border-radius: 4px;\r\n}\r\n.alert-danger[_ngcontent-%COMP%] {\r\n  color: #a94442;\r\n  background-color: #f2dede;\r\n  border-color: #ebccd1;\r\n}\r\n.msg[_ngcontent-%COMP%] {\r\n  color: blue;\r\n  background-color: whitesmoke;\r\n  border: 1px solid transparent;\r\n  border-radius: 4px;\r\n  margin-bottom: 20px;\r\n}'];