/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/render/api';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/linker/element';
import * as import3 from '../../../app/contact/contact.component';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from '../../../app/contact/contact.service';
import * as import9 from '../../../app/user.service';
import * as import10 from '@angular/core/src/metadata/view';
import * as import11 from '@angular/core/src/linker/component_factory';
import * as import12 from './contact.component.css.shim';
import * as import13 from '@angular/common/src/directives/ng_if';
import * as import14 from '../../../app/contact/awesome.pipe';
import * as import15 from '@angular/core/src/linker/template_ref';
import * as import16 from '@angular/forms/src/directives/ng_form';
import * as import17 from '@angular/forms/src/directives/ng_control_status';
import * as import18 from '../../../app/highlight.directive';
import * as import19 from '../../../app/contact/highlight.directive';
import * as import20 from '@angular/forms/src/directives/default_value_accessor';
import * as import21 from '@angular/forms/src/directives/validators';
import * as import22 from '@angular/forms/src/directives/ng_model';
import * as import23 from '@angular/core/src/linker/element_ref';
import * as import24 from '@angular/forms/src/validators';
import * as import25 from '@angular/forms/src/directives/control_value_accessor';
import * as import26 from '@angular/forms/src/directives/ng_control';
import * as import27 from '@angular/forms/src/directives/control_container';
var renderType_ContactComponent_Host:import0.RenderComponentType = (null as any);
class _View_ContactComponent_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import2.AppElement;
  _ContactComponent_0_4:import3.ContactComponent;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ContactComponent_Host0,renderType_ContactComponent_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.selectOrCreateHostElement('app-contact',rootSelector,(null as any));
    this._appEl_0 = new import2.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ContactComponent0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ContactComponent_0_4 = new import3.ContactComponent(this.parentInjector.get(import8.ContactService),this.parentInjector.get(import9.UserService));
    this._appEl_0.initComponent(this._ContactComponent_0_4,([] as any[]),compView_0);
    compView_0.create(this._ContactComponent_0_4,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import3.ContactComponent) && (0 === requestNodeIndex))) { return this._ContactComponent_0_4; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (((this.numberOfChecks === 0) && !throwOnChange)) { this._ContactComponent_0_4.ngOnInit(); }
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ContactComponent_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  if ((renderType_ContactComponent_Host === (null as any))) { (renderType_ContactComponent_Host = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ContactComponent_Host0(viewUtils,parentInjector,declarationEl);
}
export const ContactComponentNgFactory:import11.ComponentFactory<import3.ContactComponent> = new import11.ComponentFactory<import3.ContactComponent>('app-contact',viewFactory_ContactComponent_Host0,import3.ContactComponent);
const styles_ContactComponent:any[] = [import12.styles];
var renderType_ContactComponent:import0.RenderComponentType = (null as any);
class _View_ContactComponent0 extends import1.AppView<import3.ContactComponent> {
  _el_0:any;
  _text_1:any;
  _text_2:any;
  _anchor_3:any;
  /*private*/ _appEl_3:import2.AppElement;
  _TemplateRef_3_5:any;
  _NgIf_3_6:import13.NgIf;
  _text_4:any;
  _anchor_5:any;
  /*private*/ _appEl_5:import2.AppElement;
  _TemplateRef_5_5:any;
  _NgIf_5_6:import13.NgIf;
  _text_6:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  _pipe_awesome_0:import14.AwesomePipe;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ContactComponent0,renderType_ContactComponent,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'h2',(null as any));
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._text_2 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_3 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_3 = new import2.AppElement(3,(null as any),this,this._anchor_3);
    this._TemplateRef_3_5 = new import15.TemplateRef_(this._appEl_3,viewFactory_ContactComponent1);
    this._NgIf_3_6 = new import13.NgIf(this._appEl_3.vcRef,this._TemplateRef_3_5);
    this._text_4 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._anchor_5 = this.renderer.createTemplateAnchor(parentRenderNode,(null as any));
    this._appEl_5 = new import2.AppElement(5,(null as any),this,this._anchor_5);
    this._TemplateRef_5_5 = new import15.TemplateRef_(this._appEl_5,viewFactory_ContactComponent2);
    this._NgIf_5_6 = new import13.NgIf(this._appEl_5.vcRef,this._TemplateRef_5_5);
    this._text_6 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._pipe_awesome_0 = new import14.AwesomePipe();
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._text_2,
      this._anchor_3,
      this._text_4,
      this._anchor_5,
      this._text_6
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import15.TemplateRef) && (3 === requestNodeIndex))) { return this._TemplateRef_3_5; }
    if (((token === import13.NgIf) && (3 === requestNodeIndex))) { return this._NgIf_3_6; }
    if (((token === import15.TemplateRef) && (5 === requestNodeIndex))) { return this._TemplateRef_5_5; }
    if (((token === import13.NgIf) && (5 === requestNodeIndex))) { return this._NgIf_5_6; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    const currVal_1:any = this.context.msg;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this._NgIf_3_6.ngIf = currVal_1;
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this.context.contacts;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this._NgIf_5_6.ngIf = currVal_2;
      this._expr_2 = currVal_2;
    }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'Contact of ',this.context.userName,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
export function viewFactory_ContactComponent0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<import3.ContactComponent> {
  if ((renderType_ContactComponent === (null as any))) { (renderType_ContactComponent = viewUtils.createRenderComponentType('',0,import10.ViewEncapsulation.Emulated,styles_ContactComponent,{})); }
  return new _View_ContactComponent0(viewUtils,parentInjector,declarationEl);
}
class _View_ContactComponent1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ContactComponent1,renderType_ContactComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','msg');
    this._text_1 = this.renderer.createText(this._el_0,'',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.msg,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setText(this._text_1,currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ContactComponent1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ContactComponent1(viewUtils,parentInjector,declarationEl);
}
class _View_ContactComponent2 extends import1.AppView<any> {
  _el_0:any;
  _NgForm_0_3:import16.NgForm;
  _ControlContainer_0_4:any;
  _NgControlStatusGroup_0_5:import17.NgControlStatusGroup;
  _text_1:any;
  _el_2:any;
  _HighlightDirective_2_3:import18.HighlightDirective;
  _HighlightDirective_2_4:import19.HighlightDirective;
  _text_3:any;
  _text_4:any;
  _el_5:any;
  _text_6:any;
  _el_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  _DefaultValueAccessor_10_3:import20.DefaultValueAccessor;
  _RequiredValidator_10_4:import21.RequiredValidator;
  _NG_VALIDATORS_10_5:any[];
  _NG_VALUE_ACCESSOR_10_6:any[];
  _NgModel_10_7:import22.NgModel;
  _NgControl_10_8:any;
  _NgControlStatus_10_9:import17.NgControlStatus;
  _HighlightDirective_10_10:import19.HighlightDirective;
  _text_11:any;
  _el_12:any;
  _text_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _text_23:any;
  _el_24:any;
  _text_25:any;
  _text_26:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  _pipe_awesome_0_0:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_13:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_26:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement) {
    super(_View_ContactComponent2,renderType_ContactComponent,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import2.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'form',(null as any));
    this._NgForm_0_3 = new import16.NgForm((null as any),(null as any));
    this._ControlContainer_0_4 = this._NgForm_0_3;
    this._NgControlStatusGroup_0_5 = new import17.NgControlStatusGroup(this._ControlContainer_0_4);
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'h3',(null as any));
    this.renderer.setElementAttribute(this._el_2,'highlight','');
    this._HighlightDirective_2_3 = new import18.HighlightDirective(this.renderer,new import23.ElementRef(this._el_2));
    this._HighlightDirective_2_4 = new import19.HighlightDirective(this.renderer,new import23.ElementRef(this._el_2));
    this._text_3 = this.renderer.createText(this._el_2,'',(null as any));
    this._text_4 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_0,'div',(null as any));
    this.renderer.setElementAttribute(this._el_5,'class','form-group');
    this._text_6 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'label',(null as any));
    this.renderer.setElementAttribute(this._el_7,'for','name');
    this._text_8 = this.renderer.createText(this._el_7,'Name',(null as any));
    this._text_9 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_10 = this.renderer.createElement(this._el_5,'input',(null as any));
    this.renderer.setElementAttribute(this._el_10,'class','form-control');
    this.renderer.setElementAttribute(this._el_10,'name','name');
    this.renderer.setElementAttribute(this._el_10,'required','');
    this.renderer.setElementAttribute(this._el_10,'type','text');
    this._DefaultValueAccessor_10_3 = new import20.DefaultValueAccessor(this.renderer,new import23.ElementRef(this._el_10));
    this._RequiredValidator_10_4 = new import21.RequiredValidator();
    this._NG_VALIDATORS_10_5 = [this._RequiredValidator_10_4];
    this._NG_VALUE_ACCESSOR_10_6 = [this._DefaultValueAccessor_10_3];
    this._NgModel_10_7 = new import22.NgModel(this._ControlContainer_0_4,this._NG_VALIDATORS_10_5,(null as any),this._NG_VALUE_ACCESSOR_10_6);
    this._NgControl_10_8 = this._NgModel_10_7;
    this._NgControlStatus_10_9 = new import17.NgControlStatus(this._NgControl_10_8);
    this._HighlightDirective_10_10 = new import19.HighlightDirective(this.renderer,new import23.ElementRef(this._el_10));
    this._text_11 = this.renderer.createText(this._el_5,'\n    ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_5,'div',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','alert alert-danger');
    this._text_13 = this.renderer.createText(this._el_12,'\n      Name is required\n    ',(null as any));
    this._text_14 = this.renderer.createText(this._el_5,'\n  ',(null as any));
    this._text_15 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_0,'br',(null as any));
    this._text_17 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','btn btn-default');
    this.renderer.setElementAttribute(this._el_18,'type','submit');
    this._text_19 = this.renderer.createText(this._el_18,'Save',(null as any));
    this._text_20 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_21,'class','btn');
    this.renderer.setElementAttribute(this._el_21,'type','button');
    this._text_22 = this.renderer.createText(this._el_21,'Next Contact',(null as any));
    this._text_23 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_0,'button',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','btn');
    this.renderer.setElementAttribute(this._el_24,'type','button');
    this._text_25 = this.renderer.createText(this._el_24,'New Contact',(null as any));
    this._text_26 = this.renderer.createText(this._el_0,'\n',(null as any));
    var disposable_0:Function = this.renderer.listen(this._el_0,'ngSubmit',this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_0,'submit',this.eventHandler(this._handle_submit_0_1.bind(this)));
    var disposable_2:Function = this.renderer.listen(this._el_0,'reset',this.eventHandler(this._handle_reset_0_2.bind(this)));
    const subscription_0:any = this._NgForm_0_3.ngSubmit.subscribe(this.eventHandler(this._handle_ngSubmit_0_0.bind(this)));
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._pipe_awesome_0_0 = import4.pureProxy1((<_View_ContactComponent0>this.parent)._pipe_awesome_0.transform.bind((<_View_ContactComponent0>this.parent)._pipe_awesome_0));
    this._expr_9 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_10,'ngModelChange',this.eventHandler(this._handle_ngModelChange_10_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_10,'input',this.eventHandler(this._handle_input_10_1.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_10,'blur',this.eventHandler(this._handle_blur_10_2.bind(this)));
    this._expr_13 = import7.UNINITIALIZED;
    this._expr_14 = import7.UNINITIALIZED;
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    const subscription_1:any = this._NgModel_10_7.update.subscribe(this.eventHandler(this._handle_ngModelChange_10_0.bind(this)));
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_21,'click',this.eventHandler(this._handle_click_21_0.bind(this)));
    var disposable_7:Function = this.renderer.listen(this._el_24,'click',this.eventHandler(this._handle_click_24_0.bind(this)));
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import18.HighlightDirective) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._HighlightDirective_2_3; }
    if (((token === import19.HighlightDirective) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 3)))) { return this._HighlightDirective_2_4; }
    if (((token === import20.DefaultValueAccessor) && (10 === requestNodeIndex))) { return this._DefaultValueAccessor_10_3; }
    if (((token === import21.RequiredValidator) && (10 === requestNodeIndex))) { return this._RequiredValidator_10_4; }
    if (((token === import24.NG_VALIDATORS) && (10 === requestNodeIndex))) { return this._NG_VALIDATORS_10_5; }
    if (((token === import25.NG_VALUE_ACCESSOR) && (10 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_10_6; }
    if (((token === import22.NgModel) && (10 === requestNodeIndex))) { return this._NgModel_10_7; }
    if (((token === import26.NgControl) && (10 === requestNodeIndex))) { return this._NgControl_10_8; }
    if (((token === import17.NgControlStatus) && (10 === requestNodeIndex))) { return this._NgControlStatus_10_9; }
    if (((token === import19.HighlightDirective) && (10 === requestNodeIndex))) { return this._HighlightDirective_10_10; }
    if (((token === import16.NgForm) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgForm_0_3; }
    if (((token === import27.ControlContainer) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._ControlContainer_0_4; }
    if (((token === import17.NgControlStatusGroup) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._NgControlStatusGroup_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    var changes:{[key: string]:import7.SimpleChange} = (null as any);
    const valUnwrapper:any = new import7.ValueUnwrapper();
    const currVal_13:any = '';
    if (import4.checkBinding(throwOnChange,this._expr_13,currVal_13)) {
      this._RequiredValidator_10_4.required = currVal_13;
      this._expr_13 = currVal_13;
    }
    changes = (null as any);
    const currVal_15:any = 'name';
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this._NgModel_10_7.name = currVal_15;
      if ((changes === (null as any))) { (changes = {}); }
      changes['name'] = new import7.SimpleChange(this._expr_15,currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this.parent.context.contact.name;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this._NgModel_10_7.model = currVal_16;
      if ((changes === (null as any))) { (changes = {}); }
      changes['model'] = new import7.SimpleChange(this._expr_16,currVal_16);
      this._expr_16 = currVal_16;
    }
    if ((changes !== (null as any))) { this._NgModel_10_7.ngOnChanges(changes); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_3:any = this._NgControlStatusGroup_0_5.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_0,'ng-untouched',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = this._NgControlStatusGroup_0_5.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_0,'ng-touched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatusGroup_0_5.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_0,'ng-pristine',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatusGroup_0_5.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_0,'ng-dirty',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatusGroup_0_5.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_0,'ng-valid',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatusGroup_0_5.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_0,'ng-invalid',currVal_8);
      this._expr_8 = currVal_8;
    }
    valUnwrapper.reset();
    const currVal_9:any = import4.interpolate(1,'',valUnwrapper.unwrap(import4.castByValue(this._pipe_awesome_0_0,(<_View_ContactComponent0>this.parent)._pipe_awesome_0.transform)(this.parent.context.contact.name)),'');
    if ((valUnwrapper.hasWrappedValue || import4.checkBinding(throwOnChange,this._expr_9,currVal_9))) {
      this.renderer.setText(this._text_3,currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_14:any = (this._RequiredValidator_10_4.required? '': (null as any));
    if (import4.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementAttribute(this._el_10,'required',((currVal_14 == (null as any))? (null as any): currVal_14.toString()));
      this._expr_14 = currVal_14;
    }
    const currVal_17:any = this._NgControlStatus_10_9.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_10,'ng-untouched',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_10_9.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_10,'ng-touched',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_10_9.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_10,'ng-pristine',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_10_9.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_10,'ng-dirty',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_10_9.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_10,'ng-valid',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_10_9.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_10,'ng-invalid',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgModel_10_7.valid;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementProperty(this._el_12,'hidden',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:boolean = !this._NgForm_0_3.form.valid;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementProperty(this._el_18,'disabled',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_26:boolean = !this._NgForm_0_3.form.valid;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementProperty(this._el_21,'disabled',currVal_26);
      this._expr_26 = currVal_26;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_10_7.ngOnDestroy();
  }
  private _handle_ngSubmit_0_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.onSubmit()) !== false);
    return (true && pd_0);
  }
  private _handle_submit_0_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_0_3.onSubmit($event)) !== false);
    return (true && pd_0);
  }
  private _handle_reset_0_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._NgForm_0_3.onReset()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_10_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.parent.context.contact.name = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_input_10_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_10_3.onChange($event.target.value)) !== false);
    return (true && pd_0);
  }
  private _handle_blur_10_2($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DefaultValueAccessor_10_3.onTouched()) !== false);
    return (true && pd_0);
  }
  private _handle_click_21_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.next()) !== false);
    return (true && pd_0);
  }
  private _handle_click_24_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.parent.context.newContact()) !== false);
    return (true && pd_0);
  }
}
function viewFactory_ContactComponent2(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import2.AppElement):import1.AppView<any> {
  return new _View_ContactComponent2(viewUtils,parentInjector,declarationEl);
}